//@ sourceMappingURL=script.map
// Generated by CoffeeScript 1.6.1
(function() {

  (function($) {
    return $(document).ready(function() {
      var src;
      hljs.tabReplace = '  ';
      hljs.initHighlighting();
      src = $("#source");
      src.sourceDemo({
        classPref: "srcdemo",
        messageBox: $("#leftcol")
      });
      src.on("changestate", function(e, num) {
        var p;
        $("#statenumber").val(num);
        p = 100 * num / Math.max($(this).data("slides_off").length, $(this).data("slides_on").length);
        return $("#progressbar").find("div.bar").css("width", "" + p + "%");
      });
      $(document).on("keydown", function(e) {
        switch (e.keyCode) {
          case 39:
            return src.sourceDemo('next');
          case 37:
            return src.sourceDemo('prev');
        }
      });
      return $("a[rel^='prettyPhoto']").prettyPhoto({
        'social_tools': '',
        'default_height': 400
      });
    });
  })(jQuery);

}).call(this);
