//@ sourceMappingURL=script.map
// Generated by CoffeeScript 1.6.1
(function() {

  jQuery(document).ready(function() {
    var src;
    hljs.tabReplace = '  ';
    hljs.initHighlighting();
    src = jQuery("#source");
    src.sourceDemo({
      classPref: "srcdemo",
      messageBox: jQuery("#leftcol")
    });
    src.on("changestate", function(e, num) {
      var p;
      jQuery("#statenumber").val(num);
      p = 100 * num / Math.max($(this).data("slides_off").length, $(this).data("slides_on").length);
      return jQuery("#progressbar").find("div.bar").css("width", "" + p + "%");
    });
    return jQuery(document).on("keydown", function(e) {
      switch (e.keyCode) {
        case 39:
          return src.sourceDemo('next');
        case 37:
          return src.sourceDemo('prev');
      }
    });
  });

}).call(this);
